### ISSUE TITLE
Interface not showing version and use link of the core packages

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#116]
In the previous version of  the UI when entering a core package from the system tab, we had version , use link, and ports. Now only version and  use link  are showed  but they are always empty (version :undefined use link empty). We have the version of the core package in the general view but it  does not look quite good to have fields in that screen thaat are always empty or showing "undefined". 

It only happens in the system tab. When entering a non core package in "packages" it shows  the  version  (even  though it is also shown in the  general view of the installed  packages) and use link

![image](https://user-images.githubusercontent.com/21328788/46612750-bc5e9d80-cb11-11e8-8c24-2b6d38d70fbf.png)

**Comment by dapplion** [comment]
@Shelpin Thanks for reporting, added to backlog

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/87ef82defa525dccf0f3a4fa51d26f33cc62744e

**Comment by Shelpin** [comment]
This is not released yet, is it? in the machine i am using now,it does not show anything in this area. Could we include here package installation path, volumes associated and size , and in the system screen having an overview of all the packages.

**Comment by Shelpin** [comment]
working, thanks!!!
