### ISSUE TITLE
Little typo in installer

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#123]
After checking compatibilty when installing a package it says compatibile not compatible

![image](https://user-images.githubusercontent.com/21328788/46690310-3f5f2100-cc02-11e8-9996-29dbce824f9e.png)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/2a6593d060afc962e4007c1a456d0ac08968589e
