### ISSUE TITLE
Impossible to uncheck "services/libraries" in the installer screen

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#124]
When you are in the installer tab, if you check any of the libraries or services fields you can´t uncheck them anymore

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/b17226ef1a2d7a23dc35ad3a49f4fb3dcbe2d425

**Comment by Shelpin** [comment]
Working now, thanks!!
