### ISSUE TITLE
Persistent errors when installing first while ETHCHAIN is synced 

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#125]
Hi! Everytime i install a new DAppnode two errors appear until the node is synced. 

These errors does not seem to affect  the normal operation of the DAppnode, but from a user first impression point of view, it is not quite a good start seeing errors in your first contact  with the DAppnode. Would be possible not showing them  in the UI (bottom right corner) even though they still  might appear in the activity section??? 

Thanks!!

![image](https://user-images.githubusercontent.com/21328788/46729230-0025e400-cc85-11e8-9837-558a8f761e9f.png)

**Comment by Shelpin** [comment]
I already saw the fix in the new DNP ADMIN version...great!! with the text mainet sincyn it is perfect, but still using the red colour implies ALERT, what do you think about using yellow as a warning / information ?

**Comment by Shelpin** [comment]
Still when entering the activity tab the errors appear, taking in account that the activity tab is the second to be clicked by order, would be possible to eliminate or hide them so the user does not see errors when the dappnode is just installed?

**Comment by dapplion** [comment]
This issue was fixed with the last release
![issyncingmsg](https://user-images.githubusercontent.com/35266934/47013639-31505980-d148-11e8-8082-616d0623fada.jpeg)

I would not recommend hiding errors from the activity tab even if they are caused by known bugs, we may silence new ones in the future.

**Comment by dapplion** [comment]
This issue was fixed in the last release, showing a message when the chain is still syncing.

I would not recommend hiding errors, we may silence new ones.

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/commit/8e36c873860f33a4f17d6004eb40d7320c51023d

**Comment by Shelpin** [comment]
Great!!! closed!
