### ISSUE TITLE
With Kovan and Rinkeby stopped but Mainet syncing chain status appears in red

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#138]
<img width="305" alt="screen shot 2018-10-26 at 01 08 16" src="https://user-images.githubusercontent.com/21328788/47535379-a4ca3780-d8bb-11e8-9a06-7d6756d13900.png">

**Comment by dapplion** [comment]
Related to #137

**Comment by Shelpin** [comment]
I do not know exactly how both errors could interact, but yes i saw them at the  same time

**Comment by Shelpin** [comment]
Still happening in new manager and admin versions tried on 14/12/2018

**Comment by Shelpin** [comment]
Fixed!!!closing the issue!
