### ISSUE TITLE
Package tab completely grey when no package has been yet installed

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#143]
Message saying something like: Go to installer and add  your favourite packages
Would also be convenient to place the form survey link to add packages : 
https://goo.gl/forms/EjVTHu6UBWBk60Z62

Also when you still have packages installed would be coll to keep the invitation to fill the survey

**Comment by dapplion** [comment]
@Shelpin a link to the survey is a great idea! Moved to backlog

**Comment by Shelpin** [comment]
Perfect!!

**Comment by dapplion** [comment]
Partially solved with https://github.com/dappnode/DNP_ADMIN/commit/51d50358f41807e5bdb9fc02e47247e9eb620427
No package found message
In the installer, if the user looks for a package and not one is found show a message inviting the user to answer the package query

**Comment by dapplion** [comment]
Fully solved with https://github.com/dappnode/DNP_ADMIN/commit/bb84a8f017b3e45d8fea4177715d1780443664b7
No packages installed message
In the packages tab, if there are no installed packages it shows the message:
No installed DNPs yet: If you would like install a DAppNode package (DNP), go to the installer tab
![noinstalled](https://user-images.githubusercontent.com/35266934/48950017-270e5000-ef7d-11e8-8cd1-a91fc7d8fb09.jpeg)

**Comment by Shelpin** [comment]
Great!!! Thanks!!!!
