### ISSUE TITLE
Enter button to save action not responding in "Set Static IP" and "Add device"

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#144]
You cannot just press enter to save, you gotta cross the whole screen with the mouse pointer to hit "Set" or "Device"

**Comment by dapplion** [comment]
Solved with https://github.com/dappnode/DNP_ADMIN/commit/f9abc53a96fc4c38a66944b8de1c2f1f8a13206d (devices) and https://github.com/dappnode/DNP_ADMIN/commit/f1b54b2b1a302fb2fc623930a457f72cc4aaf0bc (staticIP)

**Comment by Shelpin** [comment]
Working, thanks!!!
