### ISSUE TITLE
If there is static IP don't show the IP in the popover

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#146]
If the domain is set, then it's ok to show it.
![aaaa](https://user-images.githubusercontent.com/35266934/47683949-80c76880-dbd1-11e8-82ee-469c9d0938ab.jpeg)

**Comment by dapplion** [comment]
Fixed in https://github.com/dappnode/DNP_ADMIN/commit/6fe4288cc30432b87883c4eea9b00fb1bc7f4b49

**Comment by Shelpin** [comment]
Working, thanks!!
