### ISSUE TITLE
Show size of ETHCHAIN / IPFS in Status tab

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#148]
It would be useful to have the info about the size of each installed package... in the case  of ETH full node and IPFS, in the status section alongside with CPU usage, disk etc, and for the rest of the packages as part of the information given for each core and non  core package Packages and system

**Comment by dapplion** [comment]
Good idea! Thank you @Shelpin

**Comment by Shelpin** [comment]
More than wellcome 🦁 ;)!!!!!thanks to you!

**Comment by Shelpin** [comment]
This could be freezed until the UI review..but it is definitely something to have in mind

**Comment by Shelpin** [comment]
Closing  time!!!
