### ISSUE TITLE
Rename items in the DAppStore

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#152]
"install" is there too many times, confusing when the actual install happens. The actual install happens after clicking the INSTALL button of the dedicated package install page, so have an INSTALL button only there.
In the search bar Install -> Search
In the package card Install -> Get (or similar)
![rename.jpg](https://images.zenhubusercontent.com/5affea5c4b5806bc2bd3cb7e/88a1a7bf-4e22-4a6f-a690-8a7a202e3dfb)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/1b1e64e61a62afa6ac85f0a5ff0a9ef9554d41a5

**Comment by Shelpin** [comment]
Cool!closing it !
