### ISSUE TITLE
Little Typo in system packages "ETHCAHIN"

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#157]
Hi!!! in every screen of the core packages ethcahin is written...

![image](https://user-images.githubusercontent.com/21328788/49303763-d9d53580-f4ca-11e8-9d17-2cf1ff4ba9e1.png)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/c566300b0a0b9204abc80c36cd13d2c7ae85b678
