### ISSUE TITLE
Duplicated env vars

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#165]
When installing a package from IPFS, the environment variables appear duplicated:
<img width="1685" alt="screenshot 2018-12-17 at 16 45 03" src="https://user-images.githubusercontent.com/170204/50099585-c2ae7b80-021e-11e9-8214-8db9b700d8e6.png">

**Comment by dapplion** [comment]
Solved with https://github.com/dappnode/DNP_ADMIN/commit/3a96a917988a7e735618fcfc96de76ab265a990d
