### ISSUE TITLE
When removing  ETHCHAIN after installation "Installer" section is still available

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#167]
When removing ethchain volume the installer is still accesible  and when trying to install logically gives a "mainet is syncin" error, would be nice to consider if it is better to show the same screen as  during installation rather than forcing an error.

**Comment by dapplion** [comment]
@Shelpin I don't fully understand the error. Could you please clarify the steps to recreate and provide supporting images? Thank you for reporting!

**Comment by Shelpin** [comment]
forget about it, yesterday when i tried the remove ethchain function after syncin the installer had not refreshed and that is why i did not see the first blank installer screen after removing the eth volume, now  that i had to remove the volume again it is showing the blank screen , not the full installer screen  throwing an error "mainet is syncin" if you tried to install anything.... still the current machine did not finish syncin when i removed the volume so i can´t send images now... in that image you would see the chain status with mainet syncin and the installer section with all  the Dapps showcased
