### ISSUE TITLE
Notifications not very noticeable

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#168]
With the great  new  notifications feature users can see  warnings now  about certain actions performed and its  consequnces ( removing  guest access, dowloading a new VPN profile when the IP is updated) the problem is that when  the light of the  chain status is  in i.e  yellow  and a new notification pops  up, as a yellow button appearing, is not very catchy for the  user view  and he could miss  the notification. How could we improve the attention catcher capacity of the notifications tab??

**Comment by dapplion** [comment]
@Shelpin Thanks for reporting. Please make all UX issues you find even if they are subtle and we will review them at once on the UX revision early January 2019

**Comment by dapplion** [comment]
Fixed and released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
