### ISSUE TITLE
Installing a package via  IPFS takes the user to the  install page  back , not to "go to package"

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#169]
always that you install a package via ipfs after installation the interface goes back to the "install" page not to "Go to package". Also in the installer the dapp / node appears as "get", which overwrites the former ipfs installation when youo hit it (tried updating envars in the installation and they were changed). Maybe could be a good idea to save the screen "Go to package"  and  after installation of a package (ipfs or installer) take the user directly to the package

**Comment by dapplion** [comment]
Already fixed
