### ISSUE TITLE
Bad UX for non-admin users accessing the ADMIN UI

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#174]
Non-admin users will briefly see the UI until it detects that they are not admin users and then redirect them to the non-admin user tab. This appears confusing and forced.

I propose to display a landing + loading page saying "Opening connection" while the WAMP connection is starting and when that succeeds, show the actual UI. If the connection fails then show the non-admin user tab or an error tab without the intermediate undetermined step.

**Comment by Shelpin** [comment]
No need to create this issue after today´s review just checked that you already did, thanks!!

**Comment by dapplion** [comment]
Already implemented
