### ISSUE TITLE
The dashboard info box width is too short

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#180]
The domain name is too long for the box as seen in the example: 
![cut](https://user-images.githubusercontent.com/170204/50907650-2bf16b00-1428-11e9-9c49-7bf38658d2e3.png)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/9d7fd38bc5f0e5de71c5f92c87c7a0d7faf2885c
![popover](https://user-images.githubusercontent.com/35266934/52475229-34f66900-2b9b-11e9-8304-629676bf1473.jpeg)
