### ISSUE TITLE
Add a warning when a QR code is shown

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#181]
The QR code contains all the information to connect to the VPN, so is very sensible to shoulder-surfing attacks. A photo from a not so close distance could steal the credentials.
A warning for the user discretion would be great.

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/cc58af7081141329dc84d2130dc17843078e1cc3

![shoulder surfing](https://user-images.githubusercontent.com/35266934/52477688-20b66a00-2ba3-11e9-994e-0ca87c41bb6b.jpeg)

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
