### ISSUE TITLE
I need help to solve external IP and IPFS

### ISSUE THREAD

**Issue by ganxet** [dappnode/DNP_ADMIN#184]

**Comment by dapplion** [comment]
Hi @ganxet, thanks for reaching out! Can you explain a little bit more your problem? Adding screen captures, logs, or what you are trying to achieve will help

**Comment by Shelpin** [comment]
Hi @ganxet !!! As @dapplion said we need a bit more data to help you.... if you prefer it it would be faster in  [riot](https://matrix.to/#/!KCSAWckpLbkGyPjBwp:matrix.org?via=matrix.org&via=matrix.wespr.co&via=gulik.greyfaze.net&via=status.im) or [telegram](https://t.me/dappnode) . 

In the mean time here you have some documentation about [troubleshooting](https://dappnode.github.io/DAppNodeDocs/troubleshooting/) and the complete [user guide](http://docs.dappnode.io)

**Comment by Shelpin** [comment]
Hi @ganxet !!! could you manage to solve your problem?? Ping us on the support channels if it os not the case please.Thanks!
