### ISSUE TITLE
Small misspelling

### ISSUE THREAD

**Issue by tjayrush** [dappnode/DNP_ADMIN#185]
In the system tab of the admin panel, there's a misspelling when updating the EthChain package as per attached image
<img width="233" alt="screen shot 2019-01-10 at 2 59 14 pm" src="https://user-images.githubusercontent.com/5417918/50993857-a5e92900-14e8-11e9-95df-5ce6e09442b2.png">

**Comment by dapplion** [comment]
@tjayrush Thank you so much for reporting! Fixed in https://github.com/dappnode/DNP_DAPPMANAGER/commit/cde2526fc13dff53cdd520ac8729380c0758491b
