### ISSUE TITLE
Autodiagnose tool improvement  

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#191]
When you have the disk full, all the checks are green, but still the machine does not work, maybe it  is good to include the disk space under  100 in the checked parameters. Also give the  possibilty to add the installed chains and status, and the result of the checks optionally "Add diagnose info" "Add chain data"

**Comment by dapplion** [comment]
Fixed and released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
