### ISSUE TITLE
Connecting metamask in the SDK without a metamask enabled  browser

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#192]
When you try to connect without having metamask enabled, nothing happens, it stays in "connect" without giving any warning or error message. Could we detect if the browser has metamask enabled and if not add aside the  button a message "You need to have Metamask enabled in this browser and unlocked to connect" ? Whatever other solution might help as long as the user is made aware that metamask should be active and unlocked to use the SDK feature.

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/d56beeb504685f695af883859e7bf67202bca738

![no-metamask](https://user-images.githubusercontent.com/35266934/52476062-c070f980-2b9d-11e9-9e21-a3c6d5728786.jpeg)
