### ISSUE TITLE
Typo in SDK tab

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#194]
At the bottom, the SDK tab shows the following title:

**What can I the SDK do?**

It should be -> **What can the SDK do?**

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/6f2b673c34ff619bbc81f6d363193be796d0834e

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
