### ISSUE TITLE
Very small typo on error string

### ISSUE THREAD

**Issue by tjayrush** [dappnode/DNP_ADMIN#195]
<img width="1068" alt="screen shot 2019-01-26 at 10 19 37 pm" src="https://user-images.githubusercontent.com/5417918/51795938-d0a9d180-21b8-11e9-879d-cc899352992a.png">

*Before filing a new issue, please **provide the following information**.*

## Current versions

- **ethchain.dnp.dappnode.eth**: /ipfs/QmdXpMeBbywD33USUqZnXYVTr5sS1ZqvtQGK8HCqqZbtxR
- **vpn.dnp.dappnode.eth**: 0.1.19
- **core.dnp.dappnode.eth**: 0.1.12
- **wamp.dnp.dappnode.eth**: 0.1.0
- **ethforward.dnp.dappnode.eth**: 0.1.2
- **admin.dnp.dappnode.eth**: 0.1.14
- **wifi.dnp.dappnode.eth**: 0.1.0
- **ipfs.dnp.dappnode.eth**: 0.1.4
- **bind.dnp.dappnode.eth**: 0.1.5
- **dappmanager.dnp.dappnode.eth**: 0.1.17

## System info
- **disk usage**: 14%

**Comment by dapplion** [comment]
@tjayrush Thanks for reporting! Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/commit/e476855b1ecce10b5546aefb4b66fc3b59344035

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.1
