### ISSUE TITLE
Have version info of the installed  packages

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#196]
After  installation users can´t know what version of the dockerized software correspond to our packages versioning (ie ETHCHAIN 0.1.13 = parity 2.2.9  stable) unless they jump into the package readme included in the package screen. Some users have requested this info in our channel, and  it seems something definitely useful, not only for core packages but also for packages installed via installer or  IPFS hash / ENS. It wuold be nice to have it on the package info screen. Thanks!!!

**Comment by dapplion** [comment]
Thank you for reporting. I will add the manifest's description to the package tab where, in the case of the ethchain, displays the parity version.

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
