### ISSUE TITLE
Server can’t be shut down from the UI

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#199]
If we want people to not open the console we should consider providing the ability to restart/shutdown the server from the admin UI

**Comment by dapplion** [comment]
@eduadiez Suggested this methodology https://stackoverflow.com/questions/42660690/is-it-possible-to-shut-down-the-host-machine-by-executing-a-command-on-one-of-it

**Comment by tjayrush** [comment]
I support this feature. I frequently take my dAppNode with me 'on the road'. I use it during demos of my work. The only way I know to shut down the machine is to unplug it. That cannot be the best way. I guess I could setup ssh access, but a clean way to shut down from the UI would be appreciated.

**Comment by dapplion** [comment]
Already implemented
