### ISSUE TITLE
Core package appears in system after  updating DAPPMANAGER  (0.1.20) and ADMIN (0.1.16)

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#226]
Just updated through the ADMIN UI, and the core package reappeared in  the system tab.... in the  last tests it did not appear....

![image](https://user-images.githubusercontent.com/21328788/53115580-e35cbf80-3546-11e9-9fe8-8424f3a8c8f5.png)

**Comment by dAAAb** [comment]
Same problem here! 
Even update Admin from 0.1.16 to 0.1.17 has the same issue.

**Comment by dapplion** [comment]
Fixed on https://github.com/dappnode/DNP_ADMIN/tree/v0.2.0-alpha

**Comment by Shelpin** [comment]
Checked and working!Core is not appearing anymore

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
