### ISSUE TITLE
dappmanager.dnp.dappnode.eth to 0.1.21. doesn't work correctly

### ISSUE THREAD

**Issue by minerideseama** [dappnode/DNP_ADMIN#229]
*Before filing a new issue, please **provide the following information**.*

## Current versions
- **ethchain.dnp.dappnode.eth**: 0.1.14
- **core.dnp.dappnode.eth**: 0.1.19
- **admin.dnp.dappnode.eth**: 0.1.16
- **vpn.dnp.dappnode.eth**: 0.1.21
- **ethforward.dnp.dappnode.eth**: 0.1.5
- **dappmanager.dnp.dappnode.eth**: 0.1.20
- **ipfs.dnp.dappnode.eth**: 0.1.4
- **wifi.dnp.dappnode.eth**: 0.1.0
- **bind.dnp.dappnode.eth**: 0.1.6
- **wamp.dnp.dappnode.eth**: 0.1.1

## System info
- **Disk usage**: 35%
- **Docker version**: Docker version 17.05.0-ce, build v17.05.0-ce
- **Docker compose version**: docker-compose version 1.20.1, build 5d8c71b

## Problem:

Received notification in GUI to update dappmanager.dnp.dappnode.eth to 0.1.21.
Hit update, downloading, installing, starting.
Than still on 0.1.20, so the systems keeps telling me to update.

**Comment by Shelpin** [comment]
Hi @minerideseama!! Try please to disconnect the vpn and connect it again...then empty cache before entering the Admin UI. If doing that you still have version 0.1.20 please type in the installer dappmanager.dnp.dappnode.eth and hit install please. If for any strange reason it still did not work we are happy to help,either here or in our telegram or riot (probably faster) Thanks for #nodling!!

**Comment by minerideseama** [comment]
Problem solved by:

 sudo wget -O - https://github.com/dappnode/DAppNode/releases/download/v0.1.18/dappnode_install.sh | sudo UPDATE=true bash 

Thank you guys!
