### ISSUE TITLE
Sticky popups in the Server info and status check

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#236]
In the new versions of admin when you click on the name of the server the combo never goes out unless you click again in the name of the server.  

Also if you click the chain status it gets behind the server data

![image](https://user-images.githubusercontent.com/21328788/53333414-119b2000-38f6-11e9-94f2-043745d1a192.png)

**Comment by dapplion** [comment]
Fixed at https://github.com/dappnode/DNP_ADMIN/tree/v0.2.0-alpha

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
