### ISSUE TITLE
parity node has low peer count - falls to 0 frequently - but generally stays in sync with 1-2 peers

### ISSUE THREAD

**Issue by ethgasstation** [dappnode/DNP_ADMIN#241]
*Before filing a new issue, please **provide the following information**.*

## Current versions
- **ethchain.dnp.dappnode.eth**: 0.1.14
- **wifi.dnp.dappnode.eth**: 0.1.0
- **admin.dnp.dappnode.eth**: 0.1.17
- **core.dnp.dappnode.eth**: 0.1.20
- **dappmanager.dnp.dappnode.eth**: 0.1.21
- **ethforward.dnp.dappnode.eth**: 0.1.5
- **wamp.dnp.dappnode.eth**: 0.1.1
- **vpn.dnp.dappnode.eth**: 0.1.21
- **bind.dnp.dappnode.eth**: 0.1.6
- **ipfs.dnp.dappnode.eth**: 0.1.4

## System info
- **Disk usage**: 38%
- **Docker version**: Docker version 17.05.0-ce, build v17.05.0-ce
- **Docker compose version**: docker-compose version 1.20.1, build 5d8c71b

**Comment by ethgasstation** [comment]
even after upgrading using the IPFS hash it looks like I am still running parity ethereum 2.2.10  - which seems like an outdated version. Is there a different way to force the upgrade?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ethgasstation** [comment]
Actually - i see that it auto-updated to 2.2.11 - does the version update automatically?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ethgasstation** [comment]
But it goes back to 2.2.10 after restart and then auto-updates again

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Shelpin** [comment]
Hi @ethgasstation !!! the latest version of ethchain is 0.1.14, that is the one that you had, and that you have reinstalled, there is no autoupdates, and that client is compatible with St Petersfork. Still we will publish a new ethchain package with the latest parity stable version very soon.... let us please know if you run the same issues of low peer connections.Thanks!!!

**Comment by Shelpin** [comment]
Hi again @ethgasstation ! we just published an update, and it contains Parity 2.3.8 stable (ethchain 0.1.15) you can update it through the admin UI (with the rest of the packages update, IPFS, admin, manager... )or using the ipfs hash of the package ipfs/QmZADKxEagdDEbwQgFgyuhSD1Vbp4soXMDXtNPG77pRMMC

thanks !
