### ISSUE TITLE
Donate button pointing to web without donation section

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#245]
Now the buttons just takes to the web and there is no donation info , Can we either remove it temporarily or just integrate metamask in it so people can just donate  from the ADMIN UI??

**Comment by dapplion** [comment]
TODO:
- [ ] Move the DONATE button to an encouraging test in the home page
- [ ] When clicking donate open metamask with the address prepopulated or a link to the giveth campaign
