### ISSUE TITLE
If NoNatLoopback show two profiles

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#249]
If NoNatLoopback = true, the ADMIN should fetch the profile, decrypt it and modify the domain or static IP by the Internal IP. Then offer both profiles to download directly with two buttons, or maybe a modal.

**Comment by dapplion** [comment]
Proposed solution:
Add two endpoints in admin's exposed port 8090
  - `/myip`: returns the client IP using only nginx directives
```
default_type text/plain;
return 200 "$remote_addr\n";
```
  - `/yourip`: Returns the DAppNode's IP which may be passed to the ADMIN through a volume with the DAPPMANAGER in .txt format. Currently it's not straightforward for a browser to resolve a domain to an IP.

If the ADMIN UI state says that `noNatLoopback: true`, it will append the DAppNode's internal IP in the VPN credentials URL.

Then the OpenVPN UI will check if the internal IP is in the URL and then it will use the gathered IPs to know if the client is connected in the same network as the DAppNode. In that case, it will show to profiles for download, explaining the situation.

**Comment by dapplion** [comment]
@vdo realized that this solution should also be in the first connection of the VPN, otherwise it's pointless.

**Comment by vdo** [comment]
A couple of concerns:
- This would be needed in the very first connection, which is provided with link, QR using the public domain anyway, so I'm not sure at what point would be useful.
- Giving a ovpn file for internal connectivity (a VPN within the local network) to get once another file to connect from the outside will make things way more confusing for the users.

**Comment by dapplion** [comment]
Problem: If a friend is in your house and you want to give her/him VPN credentials, it will not be possible to access the OpenVPN UI if NAT loopback is disabled.

Case 1: If you are connected in DAppNode's WIFI we can point the domain to the internal IP (problem solved)
Case 2: If you are connected to a different WIFI, that is an edge that we will choose not to cover given the solution for case 1.

**Comment by dapplion** [comment]
Closing for the solution outlined in https://github.com/dappnode/DNP_DAPPMANAGER/issues/206
