### ISSUE TITLE
Cannot upload files to dir path or relative path

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#250]
* When uploading a file without any path, it is not uploaded. It should be uploaded in the workdir of the container.

* When uploading a file with a path ending in a directory, the filename gets a random name instead of the original one. As an example:

![Screenshot_2019-03-26_15-51-24](https://user-images.githubusercontent.com/170204/55007090-1cbd9a80-4fdf-11e9-96a5-d389c78be8f3.png)

**Comment by dapplion** [comment]
Fixed and released on https://github.com/dappnode/DNP_ADMIN/releases/tag/v0.2.0
