### ISSUE TITLE
IPFS: Failed to connect to the API.

### ISSUE THREAD

**Issue by bingen** [dappnode/DNP_ADMIN#252]
When I access http://my.ipfs.dnp.dappnode.eth:5001/webui (link from DappNode admin panel) I get the following error:
```
Is your IPFS daemon running?

Failed to connect to the API.

Make sure you configure your IPFS API to allow cross-origin (CORS) requests, running the commands below:

Shell
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://my.ipfs.dnp.dappnode.eth:5001", "https://webui.ipfs.io"]'
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
$ ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentia
```
I tried to access the docker container to run those commands manually, but I was not able:
```
dappnode@dappnode:~$ docker exec -ti DAppNodeCore-ipfs.dnp.dappnode.eth bash
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
```

## Current versions
- **ethchain.dnp.dappnode.eth**: 0.1.13
- **vpn.dnp.dappnode.eth**: 0.1.21
- **ethforward.dnp.dappnode.eth**: 0.1.5
- **dappmanager.dnp.dappnode.eth**: 0.1.19
- **ipfs.dnp.dappnode.eth**: 0.1.4
- **core.dnp.dappnode.eth**: 0.1.17
- **wamp.dnp.dappnode.eth**: 0.1.1
- **admin.dnp.dappnode.eth**: 0.1.15
- **bind.dnp.dappnode.eth**: 0.1.6
- **wifi.dnp.dappnode.eth**: 0.1.0

## System info
- **Disk usage**: 10%
- **Docker version**: Docker version 17.05.0-ce, build v17.05.0-ce
- **Docker compose version**: docker-compose version 1.20.1, build 5d8c71b

**Comment by bingen** [comment]
Fixed doing this:
https://dappnode.github.io/DAppNodeDocs/what-can-you-do/#ipfs

(Thanks @eduadiez !)

**Comment by vdo** [comment]
Hi @bingen 

Just FYI, you can access the container as follows:

```
docker exec -ti  DAppNodeCore-ipfs.dnp.dappnode.eth  sh
```

**Comment by bingen** [comment]
Thanks!
