### ISSUE TITLE
Limit device name length

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#264]
In the devices section, when adding a new device, the length in the input box is not limited, allowing to input too long names. 
 For example, I could input a device with 34984 chars in it, and then it gives me a regex error:
![Screenshot_2019-05-08_09-43-25](https://user-images.githubusercontent.com/170204/57358704-49d0a180-7176-11e9-826c-7d63c2b1435b.png)

A limit of 80 chars should be more than enough

**Comment by Shelpin** [comment]
Tested and working 

![image](https://user-images.githubusercontent.com/21328788/58053022-abb9df80-7b56-11e9-8537-de447472dcd3.png)
