### ISSUE TITLE
Bitcoin chain status problem

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_ADMIN#268]
After publishing a new update of the Bitcoin package with:
```
  "chain": "bitcoin"
```
the chain status stopped working

<img width="368" alt="Screenshot 2019-05-11 at 14 58 57" src="https://user-images.githubusercontent.com/20141918/57570030-ee184980-73fd-11e9-80af-741a86b73f4c.png">

**Comment by dapplion** [comment]
@Shelpin Can you test this change please, and make sure the bitcoin RPC is able to connect?

**Comment by Shelpin** [comment]
👍👍👍👍

**Comment by dapplion** [comment]
Thank youuuu <3

**Comment by Shelpin** [comment]
I can't assess this as I do not publish packages :) still, the bitcoin package (0.18.0) is shown correctly in the chain status, I have bisq connected to it and LN working. moving to done
