### ISSUE TITLE
Status and Artis have the complete ENS as name in the installer

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#269]
The rest of the packages already show their correct name but Status and Artis still are showing the complete ENS name. 

![image](https://user-images.githubusercontent.com/21328788/57630682-59991d00-759e-11e9-88c8-d0a8ff10ee31.png)

**Comment by dapplion** [comment]
That's because they come from the public registry, no our own registry.

**Comment by dapplion** [comment]
Duplicated of https://github.com/dappnode/DNP_ADMIN/issues/320
