### ISSUE TITLE
System Update appearing in notifications tab

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#270]
when a DAppnode is first installed and you have the warning about the need of the chain to be synced, the mention system update can be confuse

![image](https://user-images.githubusercontent.com/21328788/57630868-ac72d480-759e-11e9-88fe-99365ce93308.png)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/27c1fc45b321ea63c8ef6963e7b3886c6ee302e9

**Comment by Shelpin** [comment]
tested
