### ISSUE TITLE
Use links are not appearing anymore

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#271]
In previous versions, we had info on the use link for each package in the package screen. 

Now that info is not shown anymore, taking Bitcoin example when a user installs the package he does not have any place within the UI to know what´s the address he should use  to connect to his node, also in monero, kovan, ropsten, rinkeby, in the ethchain package it is shown as endpoint.

**Comment by dapplion** [comment]
Manifests MUST follow the specs of the `links` property in order for what you consider use links to show up https://dappnode.github.io/DAppNodeDocs/manifest-reference/#links.
@eduadiez Should update the manifests according to these specs if any relevant link is missing
