### ISSUE TITLE
Scroll to bottom button in logs have dissapeared

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#276]
In the new 0.2.1 admin, the button to go to the bottom of the logs have dissapeared

![image](https://user-images.githubusercontent.com/21328788/57633205-78e67900-75a3-11e9-9cd2-f6328570e9c9.png)

**Comment by dapplion** [comment]
I totally forgot I removed it on purpose. I found a way to automatically detect when a new set of logs if received, and the UI automatically scrolls to bottom in that case, make the `SCROLL TO BOTTOM` no longer necessary.

**Comment by dapplion** [comment]
@Shelpin If you notice that the auto-scroll to bottom does not work, please open an issue with this title and clearly specifying the browser you notice the behavior + version + OS + device.
