### ISSUE TITLE
Share buttons for credentials are confusing for some users

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#277]
![image](https://user-images.githubusercontent.com/21328788/57633347-b8ad6080-75a3-11e9-8fb1-5cddd198701b.png)
Some people have asked about the new way of creating / sharing the credentials. 

Could we  make more clear, for example with alt texts in the  buttons saying 

Show QR
Copy link
Download file

**Comment by dapplion** [comment]
Related to https://github.com/dappnode/DNP_ADMIN/issues/282

**Comment by dapplion** [comment]
Solved in #282, closing for duplicate
