### ISSUE TITLE
Double separator lines in system packages

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#279]
when using chrome some random packages get a double separator line, in Safari all the lines are single, in this example see ipfs and ethchain below lines. 

![image](https://user-images.githubusercontent.com/21328788/57636825-3d9b7880-75aa-11e9-8e2a-e9bae96d1749.png)

**Comment by dapplion** [comment]
Thank for noticing this issue! Fixed with https://github.com/dappnode/DNP_ADMIN/commit/3fb220b77f22f1b8b01abcc6ad4cd0814af2c9ae
