### ISSUE TITLE
Include the long description of DNP

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#280]
Could we write About this DAppNode Package ? Not important but more clear for users  

![image](https://user-images.githubusercontent.com/21328788/57637266-42acf780-75ab-11e9-9ad8-7a699278562f.png)

**Comment by dapplion** [comment]
@Shelpin That's a matter of changing the manifest of the DNP. The first sentence should be 5 words describing the package super briefly. Then the text can be as long as necessary.

**Comment by eduadiez** [comment]
@dapplion this issue is about “About this DNP”, I think is better to write “About this DAppNodePackage”

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/03bcd40257def3c5255d5be542ad38b9adc95db5

**Comment by Shelpin** [comment]
Checked that the About this DNP is just removed and every DNP mention has been substituted by DAppNodePackage
