### ISSUE TITLE
Goerli Package throwing an error when erasing ports in the install

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#281]
If you erase the default ports the installation throws the following error, and the package is not installed

![image](https://user-images.githubusercontent.com/21328788/57639308-ec8e8300-75af-11e9-8205-bbc68bbac925.png)

![image](https://user-images.githubusercontent.com/21328788/57639406-25c6f300-75b0-11e9-83ea-73bef971b1fe.png)

**Comment by dapplion** [comment]
Thanks for reporting! A circular dependency caused an import to be empty. Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/commit/b2441f55a9a60f64c47ead51a548e055c3f7768c

**Comment by Shelpin** [comment]
Tested
