### ISSUE TITLE
SSH redirection to host

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#292]
We could allow users to ssh to the host doing a reverse tunnel with socat:

`socat TCP-LISTEN:22,FORK TCP:172.17.0.1:22`

this would allow users to connect to the dappnode's server with

`ssh dappnode@my.dappnode`

**Comment by eduadiez** [comment]
What about guests users? Since some DAppNodes use the default user/pass this could be a security problem, right?

**Comment by vdo** [comment]
Guest users should not have the SSH key or password anyway.

**Comment by dapplion** [comment]
Closing for https://github.com/dappnode/DNP_ADMIN/issues/317
