### ISSUE TITLE
Select the whole credentials link with just one click over it

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#303]
@Shelpin commented on [Thu May 23 2019](https://github.com/dappnode/DNP_VPN/issues/131)

if you don't realize the button to copy the link at the right, the natural move is clicking in the link field itself, but it does not select the whole string to be able to copy it fastly. 

This happens both in chrome and safari

---

@dapplion commented on [Thu Jun 06 2019](https://github.com/dappnode/DNP_VPN/issues/131#issuecomment-499491350)

@Shelpin Can you please re-open this issue in the DNP_ADMIN repo with an illustrative screenshot? Reference and close this one afterward.

---

@Shelpin commented on [Thu Jun 06 2019](https://github.com/dappnode/DNP_VPN/issues/131#issuecomment-499603272)

of course!moved to DNPADMIN

**Comment by Shelpin** [comment]
when you hit the link with a double click to select it and copy it, it only selects a part of the link, this screenshot is taken after doing double click over the link text

![image](https://user-images.githubusercontent.com/21328788/59055563-673c7c80-8896-11e9-8bd9-4db03ea6d53b.png)

**Comment by dapplion** [comment]
Not prioritized at the moment
