### ISSUE TITLE
Force users to change the ssh password or disable it

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#317]
Through an indirect way like a cron script that reads a file writable from the UI, modify the ssh key list and the ssh password so the DAppNode does not have the default password

**Comment by vdo** [comment]
SSH connections from the Docker range can be blocked adding:
```
DenyUsers *@172.33.0.0/16
```
to `/etc/ssh/sshd_config`

**Comment by dapplion** [comment]
@vdo Can you investigate the options and outline an action plan?

**Comment by vdo** [comment]
Action plan:

Add a call to DAPPMANAGER that will:

- Detect if `dappnode` user exists
- If it's the case, enable the "Inintial password change" feature
- Given a password from UI it will call the following command:
```
docker run --rm -it --mount type=bind,source=/etc/,target=/etc/ --privileged alpine sh -c 'echo dappnode:newpassword | chpasswd'
```
- After the password is changed, the feature should be disabled to avoid other admins to change the password.

**Comment by vdo** [comment]
A command to check if a default password is present in `/etc/shadow`

docker run --rm -it --name test -v /etc/:/etc/ --privileged alpine sh -c "grep insecur3 /etc/shadow"

**Comment by Shelpin** [comment]
Checked and working!!! awesome job guys!
