### ISSUE TITLE
Retry initial fetch on error

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#318]
There is an edge case where the WAMP and ADMIN start before the VPN and the user navigates to the admin UI during that window. If that happens, the devices initial fetch will fail.
To solve that, keep retrying the initial fetches in case they error.

**Comment by Shelpin** [comment]
How can i reproduce this one to test it :)))?

**Comment by dapplion** [comment]
@Shelpin It's very hard to test without causing an artificial error modifying the code. I did so when I patched the bug. I suggest skipping the test of this issue.

**Comment by Shelpin** [comment]
ok! will keep an eye on it!thanks!!
