### ISSUE TITLE
Reorganize the DApp Store

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#320]
- [x] Have two distinct sections: Featured, all; governed by the directory smart contract.
- [x] Show DNPs from the `dnp.dappnode.eth` repo with a verified tick
- [x] Remove library and services categories for keywords or a dedicated category option

![method-draw-image.svg](https://images.zenhubusercontent.com/5affea5c4b5806bc2bd3cb7e/ea64c8e6-e264-424a-b22a-04bd1d94b169)

**Comment by Shelpin** [comment]
I do not see the featured section, for the rest it looks beautiful,great job!!

![image](https://user-images.githubusercontent.com/21328788/60355323-64810300-99ce-11e9-8874-c971370e647b.png)

**Comment by dapplion** [comment]
@Shelpin We are working with @eduadiez right now in the smart contract that will trigger the featured section. It's not still visible without altering the WAMP calls manually.

**Comment by Shelpin** [comment]
Great then! i will wait for it to be implemented before moving it to done

**Comment by Shelpin** [comment]
please note that is some cases, the description text of the package gets truncated if the package has a  "long" description. Have a look to Raiden, Bitcoin, Lightning Network, Monero, or Vipnode. 

A solution even though a bit sloppy could be substitute get for "more" or somenthig like that, taking in accoutt that  there is a heterogeneous length of descriptions I guess it is difficult to come up with a laout that fits all the cases

![image](https://user-images.githubusercontent.com/21328788/60456892-e2e1dd00-9c3a-11e9-9cf5-6ed5739aa4e6.png)
