### ISSUE TITLE
No separation between the DApNode and the package disclaimer

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ADMIN#331]
Hey!! i just saw that the disclaimer puts all the text both from us and from Raiden without differentiating it ... look in the middle of the image how our disclaimer ends and the Raiden's one starts with separation.

![image](https://user-images.githubusercontent.com/21328788/60356370-115c7f80-99d1-11e9-96be-8e5cacb777d3.png)

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/dea70772772431e2181956a9fc803033db710e92
