### ISSUE TITLE
Can't update dappnode because of ethchain package

### ISSUE THREAD

**Issue by nathPay** [dappnode/DNP_ADMIN#368]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ethforward.dnp.dappnode.eth**: 0.2.2
- **ethchain.dnp.dappnode.eth**: 0.2.9
- **dappmanager.dnp.dappnode.eth**: 0.2.12, commit: 4c04b7b7
- **ipfs.dnp.dappnode.eth**: 0.2.4
- **core.dnp.dappnode.eth**: 0.2.12
- **wifi.dnp.dappnode.eth**: 0.2.0
- **admin.dnp.dappnode.eth**: 0.2.8, commit: 054b58cb
- **vpn.dnp.dappnode.eth**: 0.2.1, commit: 06e0ccf9
- **bind.dnp.dappnode.eth**: 0.2.0
- **wamp.dnp.dappnode.eth**: 0.2.0

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 52%

I want to update my dappnode to :
Core 0.2.14
Dappmanager: Update from 0.2.12 to 0.2.13
Ethchain: Update from 0.2.9 to 0.2.12
Ethforward: Update from 0.2.2 to 0.2.3

But at the beginning of the installation of all the package, the following error shows up:
```
Call to installPackageSafe
Reply: Command failed: docker-compose -f DNCORE/docker-compose-ethchain.yml up -d Duplicate mount points: [ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum:rw, ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum:rw]
```
```
Error: Command failed: docker-compose -f DNCORE/docker-compose-ethchain.yml up -d
Duplicate mount points: [ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum:rw, ethchaindnpdappnodeeth_data:/root/.local/share/io.parity.ethereum:rw]

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

kwargs = {
  "id": "core.dnp.dappnode.eth@latest",
  "options": {
    "BYPASS_CORE_RESTRICTION": true,
    "BYPASS_RESOLVER": true
  }
}
```
And because of that, it does not update other packages.

## What I've already tried
I've prune docker volume on the dappnode.

Do you guys have any ideas?

**Comment by eduadiez** [comment]
Hi @nathPay, please try to update the dappmanager manually first:
http://my.dappnode/#/installer/dappmanager.dnp.dappnode.eth
This should fix the problem and allow you to updated it

**Comment by nathPay** [comment]
Hi @eduadiez, Thanks for the answer.

Sadly I have the following error: 
`Error: Can't download dappmanager.dnp.dappnode.eth release: Ipfs hash not available: QmU9wVDuCVYfRgzAHCZDPGHM67hgnx1jjCMzWCUcj6wysP`

My IPFS node is alive and healthy.

**Comment by eduadiez** [comment]
Sometimes propagating IPFS hashes is hard... Do you mind to add my peer and try it again?
http://my.dappnode/#/system/add-ipfs-peer/%2Fdns4%2Fab66f2dc722412bf.dyndns.dappnode.io%2Ftcp%2F4001%2Fipfs%2FQmaBnrmDpbf6sZjTY8c3BUzZ8BXmmmRtpZJRVtHtgS7oMK
If you still having problems you can write me a DM on telegram or twitter, my handle is @eduadiez, and you can also join to our riot or telegram group to get support if you want:
http://riot.dappnode.io 
https://t.me/dappnode

**Comment by nathPay** [comment]
@eduadiez Hi ! Sorry for the late answer, I was busy thoses days...
Thanks to your dappnode it's working :)
I hope that IPFS team will find a great solution for sharing files easily.
