### ISSUE TITLE
Show IPFS hash in packages

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_ADMIN#385]
Packages installed from IPFS hash don't show it's hash in the information, and it's not possible to know which development version is installed. 
It would be nice to show it only if the package is coming from IPFS

**Comment by dapplion** [comment]
Will be fixed with https://github.com/dappnode/DNP_ADMIN/pull/382/commits/79edb3b4fd2c640ab349a62d3bdae086057ce3cf
