### ISSUE TITLE
Auto Diagnose possible false positive

### ISSUE THREAD

**Issue by nathPay** [dappnode/DNP_ADMIN#428]
#83  Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.7
- **dappmanager.dnp.dappnode.eth**: 0.2.30, commit: dc8967d2
- **core.dnp.dappnode.eth**: 0.2.34
- **bind.dnp.dappnode.eth**: 0.2.4
- **admin.dnp.dappnode.eth**: 0.2.19, commit: 875f5a7b
- **vpn.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3
- **wamp.dnp.dappnode.eth**: 0.2.2

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 14%

Since the new update of bind 0.2.4 and dappmanager 0.2.30 The auto diagnose showing the following error for the ipfs package:
`IPFS is not resolving: Error verifying IPFS: Error parsing file
Go to the system tab and make sure IPFS is running. Otherwise open the package and click 'restart'
If the problem persist make sure your disk has not run of space; IPFS may malfunction in that case.`

@vdo have the same error

Everythings seems to work well:
Restarting package don't change anything, no ipfs logs, dappnodesdk upload works well and ipfs webui is working.

It is more like a false positive because of the bind update in my opinion.

**Comment by dapplion** [comment]
@nathPay Thanks for reporting! I believe this is caused by a breaking change in the IPFS HTTP API. We've fixed the incompatibility here https://github.com/dappnode/DNP_ADMIN/commit/536b8f2249778f176197fd526aeeae030e93190b which is already released in the latest core version. Please if possible, update your DAppNode and let us know if the error is fixed.

**Comment by nathPay** [comment]
Hi, the fix is working for me ! Thanks a lot!
