### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by luisalrp** [dappnode/DNP_ADMIN#443]
Hi, I saw an the following error in the support / activity. I think it has something regarding the Internxt package I installed:

http://my.dappnode/#/installer//ipfs/QmV5G6BE6iradczdnFMrhKnhBuhE8RDGyzWWE8cehcqpeu

TypeError: Cannot read property 'split' of undefined
    at Object.parseDevicePath (/usr/src/app/src/utils/dockerComposeParsers.js:411:59)
    at volumes.map.vol (/usr/src/app/src/calls/volumesGet.js:46:42)
    at Array.map (<anonymous>)
    at /usr/src/app/src/calls/volumesGet.js:44:41
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/src/calls/volumesGet.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

kwargs = {}

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.31, commit: 9c52d86a
- **core.dnp.dappnode.eth**: 0.2.35
- **ipfs.dnp.dappnode.eth**: 0.2.9
- **admin.dnp.dappnode.eth**: 0.2.20, commit: 0cee5543
- **vpn.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3
- **bind.dnp.dappnode.eth**: 0.2.4
- **wamp.dnp.dappnode.eth**: 0.2.2

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 43%

**Comment by dapplion** [comment]
Thanks for reporting! In the next release, this issue will be fixed
