### ISSUE TITLE
Logs panel strips away info in angle brackets

### ISSUE THREAD

**Issue by cburgdorf** [dappnode/DNP_ADMIN#446]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.32, commit: 6e10ba53
- **core.dnp.dappnode.eth**: 0.2.36
- **ipfs.dnp.dappnode.eth**: 0.2.9
- **admin.dnp.dappnode.eth**: 0.2.20, commit: 0cee5543
- **bind.dnp.dappnode.eth**: 0.2.4
- **vpn.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3
- **wamp.dnp.dappnode.eth**: 0.2.2

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 40%

### What is wrong

The "Logs" panel seems to have issues logging lines with certain characters, in particular anything in angle brackets seems to be omitted. 

E.g. a line such as 

```
INFO  2020-06-18 15:56:07,677     HeaderOnlyPersist  Imported 194 headers in 0.11 seconds, new head: <BlockHeader #2894786 9f23bbac>
```

Gets printed as:

```
INFO  2020-06-18 15:56:07,677     HeaderOnlyPersist  Imported 194 headers in 0.11 seconds, new head:
```

I suspect this is coming from striping html tags out of the data but I wonder if there's anything that could be done to make it less sensitive to avoid this bug?

**Comment by cburgdorf** [comment]
@eduadiez

I think the problem is the `striptags` here which simply strips away all html tags.

https://github.com/dappnode/DNP_ADMIN/blob/0cee5543becd3de24c4173cd77210baf167656ef/build/src/src/pages/packages/components/PackageViews/Terminal.jsx#L25

I think a better approach would be to use something like https://www.npmjs.com/package/htmlspecialchars to escape all html tags so that e.g. `<BlockHeader ...>` becomes `&lt;BlockHeader ...&gt;`

Do you think that would be reasonable?

**Comment by eduadiez** [comment]
Thanks for reporting! @dapplion could you check this?

**Comment by dapplion** [comment]
@cburgdorf Good suggestion! Agree the omission of HTML characters could be more transparent. I'll do a PR soon.

**Comment by cburgdorf** [comment]
Cool! Thanks for looking into this.

**Comment by dapplion** [comment]
Fixed
