### ISSUE TITLE
Dappnode Admin webpage is empty on Safari (MacOS and iPadOS)

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DNP_ADMIN#455]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **bind.dnp.dappnode.eth**: 0.2.5
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **core.dnp.dappnode.eth**: 0.2.37

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 61%

**Comment by dapplion** [comment]
Fixed with latest version
