### ISSUE TITLE
I think I accidentally uninstalled a dependency.

### ISSUE THREAD

**Issue by KomplexMojo** [dappnode/DNP_ADMIN#466]
Whenever I open a package I get a missing parameter error.

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **undefined**: 0.2.35
- **undefined**: 0.2.39
- **undefined**: 0.2.7
- **undefined**: 0.2.4
- **undefined**: 0.2.11
- **undefined**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 40%

**Comment by dapplion** [comment]
Could you add here the exact error you see? The full stack trace or a screen capture of the error

**Comment by KomplexMojo** [comment]
Thanks for the quick response.  I was installing a few packages, trying them, and uninstalling them while my Geth node was sync'ing.  Now that it is fully sync'd things are back up and there is no trace of this issue, or any others.  I was seeing the error on my phone so it was a bit cumbersome to grab the exact message.  If it arises again, I'll grab a screenshot and post.

Thanks again!
