### ISSUE TITLE
IPFS is not resolving

### ISSUE THREAD

**Issue by marshallepie** [dappnode/DNP_ADMIN#467]
Hi Nodlers
Im so excited.
I managed to install Dappnode on my HP Z240 Small Form Factor Workstation intel I7, 8Gb ram 1Tb external ssd. 

Its been Syncing for 2 days. Sweet!
Thanks Dappnode gurus! Youre the best.

Anyhow please help:

*Here is **my system info**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **bind.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316

## System info
- **Disk usage**: 27%

After the install my auto diagnostics is throwing some messages  like so:

![Screenshot_2020-11-20 DAppNode Admin(1)](https://user-images.githubusercontent.com/12866205/99784263-7a3b1f00-2b13-11eb-8ed3-e40108ca3a8b.png)

The IPFS Issue appeared this morning but the Ports issues have been there since the install.

Is the IPFS issue related to the ports issue?

My network is somewhat erratic with two gateway hops on my lan.
I have forwarded ports 1194 and 8092 on both.
Do I need to tamper with Ports settings on The Dappnode admin ui?

Any help will be much appreciated.

**Comment by marshallepie** [comment]
My machine eventually stopped functioning and crashed..
i left it for a while and then rebooted it this morning and all is fine. yay!
Now just remembered i did change ports on the router to suit dappnode requirements.(without rebooting the server)
1194 udp
8092 tcp
wonder if this is why. 
Sorry newbee server admin here.
Sorry to have wasted your time. 

![image](https://user-images.githubusercontent.com/12866205/99874447-00bd3280-2be0-11eb-9eb9-cef9238e4cc4.png)

**Comment by marshallepie** [comment]
**Sorted**

**Comment by dapplion** [comment]
@marshallepie So glad you could fix the issue, let us know of any other issue you encounter.
