### ISSUE TITLE
QR isn't showing well on mobile devices

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_ADMIN#76]
![img_7164](https://user-images.githubusercontent.com/20141918/41840065-17624a06-7865-11e8-9585-52e3a82f5d30.JPG)

**Comment by dapplion** [comment]
TODO: install a desktop tester to check the web on iPhone environments

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/003619358579c130b711f359f8b529835280ab6c
