### ISSUE TITLE
The non-admin landing page never shows up

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#88]
The crossbar handler seems to fail to detect a connection error and that it is caused by a non-authenticated user

**Comment by Shelpin** [comment]
Hey!!! reopening this  one...now when accesing  to the admin ui without admin privileges, it shows for a second the UI and then the screen switches to "It seems you don´t have access". It is not very important but at  an appearance level it is not very good, it would be great if this can be fine tuned, so the user do not see for a second the ADMIN UI and then he is kicked out, but he is directly taken to the non-admin page.

**Comment by dapplion** [comment]
@Shelpin thanks for reporting the issue but it's better practice to only reopen issues when the exact issue happens again. In this case the issue is about the UX experience on how non-admin users perceive the ADMIN ui. I'm closing this issue in favor of https://github.com/dappnode/DNP_ADMIN/issues/174
